name: Swift Workflow


on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: [ubuntu-latest, macos-latest]
     swift-version: ["5.6.1"]
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test
