name: Swift Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:  ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Swift
        uses: swift-actions/setup-swift@v3
        with:
          swift-version: '5.0'
          
      - name: Build
        run: swift build

      - name: Run Tests
        run: swift test
